version: 2
jobs:
  build:
    working_directory: ~/todo-kotlin/todoapp
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout:
          path: ~/todo-kotlin
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: |
            ./gradlew androidDependencies
      - run:
          name: Lint and Test
          command: |
            ./gradlew lint test
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - store_artifacts:
          path: app/build/reports
          destination: app-reports
      - store_test_results:
          path: app/build/test-results

      - run:
          name: KeyStore
          command: echo $RELEASE_KEYSTORE | base64 --decode > app/release.keystore

      - run:
          name: Build debug APK and release APK
          command: |
            ./gradlew assembleDebug
            ./gradlew assembleRelease

      - store_artifacts:
          path: app/build/outputs/apk/prod/release/app-prod-release.apk
          destination: app-release.apk

      - store_artifacts:
          path: app/build/outputs/mapping/

      - run:
          name: Store Google Service Account
          command: echo $GCLOUD_SERVICE_KEY | base64 --decode > app/client-secret.json

      - run:
          name: Authorize gcloud and set config defaults
          command: |
            gcloud auth activate-service-account --key-file app/client-secret.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}

      - run:
          name: Test with Firebase Test Lab
          command: |
            gcloud firebase test android run \
              --type robo \
              --app app/build/outputs/apk/prod/release/app-prod-release.apk \
              --device model=Nexus6,version=21,locale=en,orientation=portrait \
              --device model=Nexus7,version=19,locale=en,orientation=landscape \
              --results-bucket ${GOOGLE_PROJECT_ID}.appspot.com

workflows:
  version: 2
  build:
    jobs:
      - build
